export default [
  { "code": "af", "en": "Afrikaans", "zh": "南非语", "th": "อัฟริกันส์" },
  { "code": "af-ZA", "en": "Afrikaans (South Africa)", "zh": "南非语", "th": "อัฟริกันส์ (แอฟริกาใต้)" },
  { "code": "ar", "en": "Arabic", "zh": "阿拉伯语", "th": "อาราบิก" },
  { "code": "ar-AE", "en": "Arabic (U.A.E.)", "zh": "阿拉伯语(阿联酋)", "th": "อาราบิก (สหรัฐอาหรับเอมิเรตส์)" },
  { "code": "ar-BH", "en": "Arabic (Bahrain)", "zh": "阿拉伯语(巴林)", "th": "อาราบิก (บาห์เรน)" },
  { "code": "ar-DZ", "en": "Arabic (Algeria)", "zh": "阿拉伯语(阿尔及利亚)", "th": "อาราบิก (อัลจีเรีย)" },
  { "code": "ar-EG", "en": "Arabic (Egypt)", "zh": "阿拉伯语(埃及)", "th": "อาราบิก (อียิปต์)" },
  { "code": "ar-IQ", "en": "Arabic (Iraq)", "zh": "阿拉伯语(伊拉克)", "th": "อาราบิก (อิรัก)" },
  { "code": "ar-JO", "en": "Arabic (Jordan)", "zh": "阿拉伯语(约旦)", "th": "อาราบิก (จอร์แดน)" },
  { "code": "ar-KW", "en": "Arabic (Kuwait)", "zh": "阿拉伯语(科威特)", "th": "อาราบิก (คูเวต)" },
  { "code": "ar-LB", "en": "Arabic (Lebanon)", "zh": "阿拉伯语(黎巴嫩)", "th": "อาราบิก (เลบานอน)" },
  { "code": "ar-LY", "en": "Arabic (Libya)", "zh": "阿拉伯语(利比亚)", "th": "อาราบิก (ลิเบีย)" },
  { "code": "ar-MA", "en": "Arabic (Morocco)", "zh": "阿拉伯语(摩洛哥)", "th": "อาราบิก (โมร็อกโก)" },
  { "code": "ar-OM", "en": "Arabic (Oman)", "zh": "阿拉伯语(阿曼)", "th": "อาราบิก (โอมาน)" },
  { "code": "ar-QA", "en": "Arabic (Qatar)", "zh": "阿拉伯语(卡塔尔)", "th": "อาราบิก (คาตาร์)" },
  { "code": "ar-SA", "en": "Arabic (Saudi Arabia)", "zh": "阿拉伯语(沙特阿拉伯)", "th": "อาราบิก (ซาอุดีอาระเบีย)" },
  { "code": "ar-SY", "en": "Arabic (Syria)", "zh": "阿拉伯语(叙利亚)", "th": "อาราบิก (ซีเรีย)" },
  { "code": "ar-TN", "en": "Arabic (Tunisia)", "zh": "阿拉伯语(突尼斯)", "th": "อาราบิก (ทูนิเซีย)" },
  { "code": "ar-YE", "en": "Arabic (Yemen)", "zh": "阿拉伯语(也门)", "th": "อาราบิก (เยเมน)" },
  { "code": "az", "en": "Azeri (Latin)", "zh": "阿塞拜疆语", "th": "อาเซอร์ไบจัน (ละติน)" },
  { "code": "az-AZ", "en": "Azeri (Cyrillic) (Azerbaijan)", "zh": "阿塞拜疆语(西里尔文)", "th": "อาเซอร์ไบจัน (ไซริลลิก) (อาเซอร์ไบจาน)" },
  { "code": "be", "en": "Belarusian", "zh": "白俄罗斯语", "th": "เบลารุส" },
  { "code": "be-BY", "en": "Belarusian (Belarus)", "zh": "白俄罗斯语", "th": "เบลารุส (เบลารุส)" },
  { "code": "bg", "en": "Bulgarian", "zh": "保加利亚语", "th": "บัลแกเรีย" },
  { "code": "bg-BG", "en": "Bulgarian (Bulgaria)", "zh": "保加利亚语", "th": "บัลแกเรีย (บัลแกเรีย)" },
  { "code": "bs-BA", "en": "Bosnian (Bosnia and Herzegovina)", "zh": "波斯尼亚语(波斯尼亚和黑塞哥维那)", "th": "บอสเนีย (บอสเนียและเฮอร์เซโกวินา)" },
  { "code": "ca", "en": "Catalan", "zh": "加泰罗尼亚语", "th": "คาตาลัน" },
  { "code": "ca-ES", "en": "Catalan (Spain)", "zh": "加泰罗尼亚语", "th": "คาตาลัน (สเปน)" },
  { "code": "cs", "en": "Czech", "zh": "捷克语", "th": "เช็ก" },
  { "code": "cs-CZ", "en": "Czech (Czech Republic)", "zh": "捷克语", "th": "เช็ก (สาธารณรัฐเช็ก)" },
  { "code": "cy", "en": "Welsh", "zh": "威尔士语", "th": "เวล์ช" },
  { "code": "cy-GB", "en": "Welsh (United Kingdom)", "zh": "威尔士语", "th": "เวล์ช (สหราชอาณาจักร)" },
  { "code": "da", "en": "Danish", "zh": "丹麦语", "th": "เดนมาร์ก" },
  { "code": "da-DK", "en": "Danish (Denmark)", "zh": "丹麦语", "th": "เดนมาร์ก (เดนมาร์ก)" },
  { "code": "de", "en": "German", "zh": "德语", "th": "เยอรมัน" },
  { "code": "de-AT", "en": "German (Austria)", "zh": "德语(奥地利)", "th": "เยอรมัน (ออสเตรีย)" },
  { "code": "de-CH", "en": "German (Switzerland)", "zh": "德语(瑞士)", "th": "เยอรมัน (สวิสเซอร์แลนด์)" },
  { "code": "de-DE", "en": "German (Germany)", "zh": "德语(德国)", "th": "เยอรมัน (เยอรมนี)" },
  { "code": "de-LI", "en": "German (Liechtenstein)", "zh": "德语(列支敦士登)", "th": "เยอรมัน (ลิกเตนสไตน์)" },
  { "code": "de-LU", "en": "German (Luxembourg)", "zh": "德语(卢森堡)", "th": "เยอรมัน (ลักเซมเบิร์ก)" },
  { "code": "dv", "en": "Divehi", "zh": "迪维希语", "th": "ดีเวหี" },
  { "code": "dv-MV", "en": "Divehi (Maldives)", "zh": "迪维希语", "th": "ดีเวหี (มัลดีฟส์)" },
  { "code": "el", "en": "Greek", "zh": "希腊语", "th": "กรีก" },
  { "code": "el-GR", "en": "Greek (Greece)", "zh": "希腊语", "th": "กรีก (กรีซ)" },
  { "code": "en", "en": "English", "zh": "英语", "th": "อังกฤษ" },
  { "code": "en-AU", "en": "English (Australia)", "zh": "英语(澳大利亚)", "th": "อังกฤษ (ออสเตรเลีย)" },
  { "code": "en-BZ", "en": "English (Belize)", "zh": "英语(伯利兹)", "th": "อังกฤษ (เบลีซ)" },
  { "code": "en-CA", "en": "English (Canada)", "zh": "英语(加拿大)", "th": "อังกฤษ (แคนาดา)" },
  { "code": "en-CB", "en": "English (Caribbean)", "zh": "英语(加勒比海)", "th": "อังกฤษ (คาริบเบียน)" },
  { "code": "en-GB", "en": "English (United Kingdom)", "zh": "英语(英国)", "th": "อังกฤษ (สหราชอาณาจักร)" },
  { "code": "en-IE", "en": "English (Ireland)", "zh": "英语(爱尔兰)", "th": "อังกฤษ (ไอร์แลนด์)" },
  { "code": "en-IN", "en": "English (India)", "zh": "英语(印度)", "th": "อังกฤษ (อินเดีย)" },
  { "code": "en-JM", "en": "English (Jamaica)", "zh": "英语(牙买加)", "th": "อังกฤษ (จาไมกา)" },
  { "code": "en-NZ", "en": "English (New Zealand)", "zh": "英语(新西兰)", "th": "อังกฤษ (นิวซีแลนด์)" },
  { "code": "en-PH", "en": "English (Philippines)", "zh": "英语(菲律宾)", "th": "อังกฤษ (ฟิลิปปินส์)" },
  { "code": "en-TT", "en": "English (Trinidad and Tobago)", "zh": "英语(特立尼达和多巴哥)", "th": "อังกฤษ (ตรินิแดดและโตเบโก)" },
  { "code": "en-US", "en": "English (United States)", "zh": "英语(美国)", "th": "อังกฤษ (สหรัฐอเมริกา)" },
  { "code": "en-ZA", "en": "English (South Africa)", "zh": "英语(南非)", "th": "อังกฤษ (แอฟริกาใต้)" },
  { "code": "en-ZW", "en": "English (Zimbabwe)", "zh": "英语(津巴布韦)", "th": "อังกฤษ (ซิมบับเว)" },
  { "code": "eo", "en": "Esperanto", "zh": "世界语", "th": "เอสเปรันโต" },
  { "code": "es", "en": "Spanish", "zh": "西班牙语", "th": "สเปน" },
  { "code": "es-AR", "en": "Spanish (Argentina)", "zh": "西班牙语(阿根廷)", "th": "สเปน (อาร์เจนตินา)" },
  { "code": "es-BO", "en": "Spanish (Bolivia)", "zh": "西班牙语(玻利维亚)", "th": "สเปน (โบลิเวีย)" },
  { "code": "es-CL", "en": "Spanish (Chile)", "zh": "西班牙语(智利)", "th": "สเปน (ชิลี)" },
  { "code": "es-CO", "en": "Spanish (Colombia)", "zh": "西班牙语(哥伦比亚)", "th": "สเปน (โคลัมเบีย)" },
  { "code": "es-CR", "en": "Spanish (Costa Rica)", "zh": "西班牙语(哥斯达黎加)", "th": "สเปน (โคสตาริกา)" },
  { "code": "es-DO", "en": "Spanish (Dominican Republic)", "zh": "西班牙语(多米尼加共和国)", "th": "สเปน (สาธารณรัฐโดมินกัน)" },
  { "code": "es-EC", "en": "Spanish (Ecuador)", "zh": "西班牙语(厄瓜多尔)", "th": "สเปน (เอกวาดอร์)" },
  { "code": "es-ES", "en": "Spanish (Spain)", "zh": "西班牙语(西班牙)", "th": "สเปน (สเปน)" },
  { "code": "es-GT", "en": "Spanish (Guatemala)", "zh": "西班牙语(危地马拉)", "th": "สเปน (กัวเตมาลา)" },
  { "code": "es-HN", "en": "Spanish (Honduras)", "zh": "西班牙语(洪都拉斯)", "th": "สเปน (ฮอนดูรัส)" },
  { "code": "es-MX", "en": "Spanish (Mexico)", "zh": "西班牙语(墨西哥)", "th": "สเปน (เม็กซิโก)" },
  { "code": "es-NI", "en": "Spanish (Nicaragua)", "zh": "西班牙语(尼加拉瓜)", "th": "สเปน (นิการากัว)" },
  { "code": "es-PA", "en": "Spanish (Panama)", "zh": "西班牙语(巴拿马)", "th": "สเปน (ปานามา)" },
  { "code": "es-PE", "en": "Spanish (Peru)", "zh": "西班牙语(秘鲁)", "th": "สเปน (เปรู)" },
  { "code": "es-PR", "en": "Spanish (Puerto Rico)", "zh": "西班牙语(波多黎各)", "th": "สเปน (เปอร์โตริโก)" },
  { "code": "es-PY", "en": "Spanish (Paraguay)", "zh": "西班牙语(巴拉圭)", "th": "สเปน (ปารากวัย)" },
  { "code": "es-SV", "en": "Spanish (El Salvador)", "zh": "西班牙语(萨尔瓦多)", "th": "สเปน (เอลซัลวาดอร์)" },
  { "code": "es-UY", "en": "Spanish (Uruguay)", "zh": "西班牙语(乌拉圭)", "th": "สเปน (อุรุกวัย)" },
  { "code": "es-VE", "en": "Spanish (Venezuela)", "zh": "西班牙语(委内瑞拉)", "th": "สเปน (เวเนซุเอลา)" },
  { "code": "et", "en": "Estonian", "zh": "爱沙尼亚语", "th": "เอสโตเนีย" },
  { "code": "et-EE", "en": "Estonian (Estonia)", "zh": "爱沙尼亚语", "th": "เอสโตเนีย (เอสโตเนีย)" },
  { "code": "eu", "en": "Basque", "zh": "巴斯克语", "th": "บาสก์" },
  { "code": "eu-ES", "en": "Basque (Spain)", "zh": "巴斯克语", "th": "บาสก์ (สเปน)" },
  { "code": "fa", "en": "Farsi", "zh": "波斯语", "th": "فارسی" },
  { "code": "fa-IR", "en": "Farsi (Iran)", "zh": "波斯语", "th": "فارسی (อิหร่าน)" },
  { "code": "fi", "en": "Finnish", "zh": "芬兰语", "th": "ฟินแลนด์" },
  { "code": "fi-FI", "en": "Finnish (Finland)", "zh": "芬兰语", "th": "ฟินแลนด์ (ฟินแลนด์)" },
  { "code": "fo", "en": "Faroese", "zh": "法罗语", "th": "ฟาโรอีส์" },
  { "code": "fo-FO", "en": "Faroese (Faroe Islands)", "zh": "法罗语", "th": "ฟาโรอีส์ (หมู่เกาะฟาโร)" },
  { "code": "fr", "en": "French", "zh": "法语", "th": "ฝรั่งเศส" },
  { "code": "fr-BE", "en": "French (Belgium)", "zh": "法语(比利时)", "th": "ฝรั่งเศส (เบลเยียม)" },
  { "code": "fr-CA", "en": "French (Canada)", "zh": "法语(加拿大)", "th": "ฝรั่งเศส (แคนาดา)" },
  { "code": "fr-CH", "en": "French (Switzerland)", "zh": "法语(瑞士)", "th": "ฝรั่งเศส (สวิสเซอร์แลนด์)" },
  { "code": "fr-FR", "en": "French (France)", "zh": "法语(法国)", "th": "ฝรั่งเศส (ฝรั่งเศส)" },
  { "code": "fr-LU", "en": "French (Luxembourg)", "zh": "法语(卢森堡)", "th": "ฝรั่งเศส (ลักเซมเบิร์ก)" },
  { "code": "fr-MC", "en": "French (Monaco)", "zh": "法语(摩纳哥)", "th": "ฝรั่งเศส (โมนาโก)" },
  { "code": "gl", "en": "Galician", "zh": "加利西亚语", "th": "กาลิเซีย" },
  { "code": "gl-ES", "en": "Galician (Spain)", "zh": "加利西亚语", "th": "กาลิเซีย (สเปน)" },
  { "code": "gu", "en": "Gujarati", "zh": "古吉拉特语", "th": "กุจาราตี" },
  { "code": "gu-IN", "en": "Gujarati (India)", "zh": "古吉拉特语", "th": "กุจาราตี (อินเดีย)" },
  { "code": "he", "en": "Hebrew", "zh": "希伯来语", "th": "ฮีบรู" },
  { "code": "he-IL", "en": "Hebrew (Israel)", "zh": "希伯来语", "th": "ฮีบรู (อิสราเอล)" },
  { "code": "hi", "en": "Hindi", "zh": "印地语", "th": "ฮินดี" },
  { "code": "hi-IN", "en": "Hindi (India)", "zh": "印地语", "th": "ฮินดี (อินเดีย)" },
  { "code": "hr", "en": "Croatian", "zh": "克罗地亚语", "th": "โครเอเชีย" },
  { "code": "hr-BA", "en": "Croatian (Bosnia and Herzegovina)", "zh": "克罗地亚语(波斯尼亚和黑塞哥维那)", "th": "โครเอเชีย (บอสเนียและเฮอร์เซโกวินา)" },
  { "code": "hr-HR", "en": "Croatian (Croatia)", "zh": "克罗地亚语", "th": "โครเอเชีย (โครเอเชีย)" },
  { "code": "hu", "en": "Hungarian", "zh": "匈牙利语", "th": "ฮังการี" },
  { "code": "hu-HU", "en": "Hungarian (Hungary)", "zh": "匈牙利语", "th": "ฮังการี (ฮังการี)" },
  { "code": "hy", "en": "Armenian", "zh": "亚美尼亚语", "th": "อาร์เมเนีย" },
  { "code": "hy-AM", "en": "Armenian (Armenia)", "zh": "亚美尼亚语", "th": "อาร์เมเนีย (อาร์เมเนีย)" },
  { "code": "id", "en": "Indonesian", "zh": "印尼语", "th": "อินโดนีเซีย" },
  { "code": "id-ID", "en": "Indonesian (Indonesia)", "zh": "印尼语", "th": "อินโดนีเซีย (อินโดนีเซีย)" },
  { "code": "is", "en": "Icelandic", "zh": "冰岛语", "th": "ไอซ์แลนด์" },
  { "code": "is-IS", "en": "Icelandic (Iceland)", "zh": "冰岛语", "th": "ไอซ์แลนด์ (ไอซ์แลนด์)" },
  { "code": "it", "en": "Italian", "zh": "意大利语", "th": "อิตาลี" },
  { "code": "it-CH", "en": "Italian (Switzerland)", "zh": "意大利语(瑞士)", "th": "อิตาลี (สวิสเซอร์แลนด์)" },
  { "code": "it-IT", "en": "Italian (Italy)", "zh": "意大利语(意大利)", "th": "อิตาลี (อิตาลี)" },
  { "code": "ja", "en": "Japanese", "zh": "日语", "th": "ญี่ปุ่น" },
  { "code": "ja-JP", "en": "Japanese (Japan)", "zh": "日语", "th": "ญี่ปุ่น (ญี่ปุ่น)" },
  { "code": "ka", "en": "Georgian", "zh": "格鲁吉亚语", "th": "จอร์เจีย" },
  { "code": "ka-GE", "en": "Georgian (Georgia)", "zh": "格鲁吉亚语", "th": "จอร์เจีย (จอร์เจีย)" },
  { "code": "kk", "en": "Kazakh", "zh": "哈萨克语", "th": "คาซัค" },
  { "code": "kk-KZ", "en": "Kazakh (Kazakhstan)", "zh": "哈萨克语", "th": "คาซัค (คาซัคสถาน)" },
  { "code": "kn", "en": "Kannada", "zh": "卡纳达语", "th": "กันนาดา" },
  { "code": "kn-IN", "en": "Kannada (India)", "zh": "卡纳达语", "th": "กันนาดา (อินเดีย)" },
  { "code": "ko", "en": "Korean", "zh": "韩语", "th": "เกาหลี" },
  { "code": "ko-KR", "en": "Korean (South Korea)", "zh": "韩语", "th": "เกาหลี (เกาหลีใต้)" },
  { "code": "kok", "en": "Konkani", "zh": "孔卡尼语", "th": "โคนกานี" },
  { "code": "kok-IN", "en": "Konkani (India)", "zh": "孔卡尼语", "th": "โคนกานี (อินเดีย)" },
  { "code": "ky", "en": "Kyrgyz", "zh": "吉尔吉斯语", "th": "กีร์กิส" },
  { "code": "ky-KG", "en": "Kyrgyz (Kyrgyzstan)", "zh": "吉尔吉斯语", "th": "กีร์กิส (กีร์กิสสถาน)" },
  { "code": "lt", "en": "Lithuanian", "zh": "立陶宛语", "th": "ลิทัวเนีย" },
  { "code": "lt-LT", "en": "Lithuanian (Lithuania)", "zh": "立陶宛语", "th": "ลิทัวเนีย (ลิทัวเนีย)" },
  { "code": "lv", "en": "Latvian", "zh": "拉脱维亚语", "th": "ลัตเวีย" },
  { "code": "lv-LV", "en": "Latvian (Latvia)", "zh": "拉脱维亚语", "th": "ลัตเวีย (ลัตเวีย)" },
  { "code": "mi", "en": "Maori", "zh": "毛利语", "th": "มอริ" },
  { "code": "mi-NZ", "en": "Maori (New Zealand)", "zh": "毛利语", "th": "มอริ (นิวซีแลนด์)" },
  { "code": "mk", "en": "Macedonian", "zh": "马其顿语", "th": "แมเซโดเนีย" },
  { "code": "mk-MK", "en": "Macedonian (North Macedonia)", "zh": "马其顿语", "th": "แมเซโดเนีย (แมเซโดเนียเหนือ)" },
  { "code": "mn", "en": "Mongolian", "zh": "蒙古语", "th": "มองโกล" },
  { "code": "mn-MN", "en": "Mongolian (Mongolia)", "zh": "蒙古语", "th": "มองโกล (มองโกล)" },
  { "code": "mr", "en": "Marathi", "zh": "马拉地语", "th": "มาราธี" },
  { "code": "mr-IN", "en": "Marathi (India)", "zh": "马拉地语", "th": "มาราธี (อินเดีย)" },
  { "code": "ms", "en": "Malay", "zh": "马来语", "th": "มลายู" },
  { "code": "ms-BN", "en": "Malay (Brunei)", "zh": "马来语(文莱)", "th": "มลายู (บรูไน)" },
  { "code": "ms-MY", "en": "Malay (Malaysia)", "zh": "马来语(马来西亚)", "th": "มลายู (มาเลเซีย)" },
  { "code": "mt", "en": "Maltese", "zh": "马耳他语", "th": "มอลตา" },
  { "code": "mt-MT", "en": "Maltese (Malta)", "zh": "马耳他语", "th": "มอลตา (มอลตา)" },
  { "code": "nb", "en": "Norwegian (Bokmål)", "zh": "挪威语(书面挪威语)", "th": "นอร์เวย์ (บอคมาล)" },
  { "code": "nb-NO", "en": "Norwegian (Bokmål) (Norway)", "zh": "挪威语(书面挪威语)(挪威)", "th": "นอร์เวย์ (บอคมาล) (นอร์เวย์)" },
  { "code": "nl", "en": "Dutch", "zh": "荷兰语", "th": "ดัตช์" },
  { "code": "nl-BE", "en": "Dutch (Belgium)", "zh": "荷兰语(比利时)", "th": "ดัตช์ (เบลเยียม)" },
  { "code": "nl-NL", "en": "Dutch (Netherlands)", "zh": "荷兰语(荷兰)", "th": "ดัตช์ (เนเธอร์แลนด์)" },
  { "code": "nn-NO", "en": "Norwegian (Nynorsk) (Norway)", "zh": "挪威语(新挪威语)(挪威)", "th": "นอร์เวย์ (นายนอร์สก) (นอร์เวย์)" },
  { "code": "ns", "en": "Northern Sotho", "zh": "北索托语", "th": "โซโทเหนือ" },
  { "code": "ns-ZA", "en": "Northern Sotho (South Africa)", "zh": "北索托语", "th": "โซโทเหนือ (แอฟริกาใต้)" },
  { "code": "pa", "en": "Punjabi", "zh": "旁遮普语", "th": "ปันจาบี" },
  { "code": "pa-IN", "en": "Punjabi (India)", "zh": "旁遮普语", "th": "ปันจาบี (อินเดีย)" },
  { "code": "pl", "en": "Polish", "zh": "波兰语", "th": "โปแลนด์" },
  { "code": "pl-PL", "en": "Polish (Poland)", "zh": "波兰语", "th": "โปแลนด์ (โปแลนด์)" },
  { "code": "pt", "en": "Portuguese", "zh": "葡萄牙语", "th": "โปรตุเกส" },
  { "code": "pt-BR", "en": "Portuguese (Brazil)", "zh": "葡萄牙语(巴西)", "th": "โปรตุเกส (บราซิล)" },
  { "code": "pt-PT", "en": "Portuguese (Portugal)", "zh": "葡萄牙语(葡萄牙)", "th": "โปรตุเกส (โปรตุเกส)" },
  { "code": "qu", "en": "Quechua", "zh": "克丘亚语", "th": "เควชัว" },
  { "code": "qu-BO", "en": "Quechua (Bolivia)", "zh": "克丘亚语(玻利维亚)", "th": "เควชัว (โบลิเวีย)" },
  { "code": "qu-EC", "en": "Quechua (Ecuador)", "zh": "克丘亚语(厄瓜多尔)", "th": "เควชัว (เอกวาดอร์)" },
  { "code": "qu-PE", "en": "Quechua (Peru)", "zh": "克丘亚语(秘鲁)", "th": "เควชัว (เปรู)" },
  { "code": "ro", "en": "Romanian", "zh": "罗马尼亚语", "th": "โรมาเนีย" },
  { "code": "ro-RO", "en": "Romanian (Romania)", "zh": "罗马尼亚语", "th": "โรมาเนีย (โรมาเนีย)" },
];