export default [
  { "code": "af", "en": "Afrikaans", "zh": "南非语", "th": "อัฟริกันส์", "id": "Afrikaans" },
  { "code": "af-ZA", "en": "Afrikaans (South Africa)", "zh": "南非语", "th": "อัฟริกันส์ (แอฟริกาใต้)", "id": "Afrikaans (Afrika Selatan)" },
  { "code": "ar", "en": "Arabic", "zh": "阿拉伯语", "th": "อาราบิก", "id": "Bahasa Arab" },
  { "code": "ar-AE", "en": "Arabic (U.A.E.)", "zh": "阿拉伯语(阿联酋)", "th": "อาราบิก (สหรัฐอาหรับเอมิเรตส์)", "id": "Bahasa Arab (UAE)" },
  { "code": "ar-BH", "en": "Arabic (Bahrain)", "zh": "阿拉伯语(巴林)", "th": "อาราบิก (บาห์เรน)", "id": "Bahasa Arab (Bahrain)" },
  { "code": "ar-DZ", "en": "Arabic (Algeria)", "zh": "阿拉伯语(阿尔及利亚)", "th": "อาราบิก (อัลจีเรีย)", "id": "Bahasa Arab (Aljazair)" },
  { "code": "ar-EG", "en": "Arabic (Egypt)", "zh": "阿拉伯语(埃及)", "th": "อาราบิก (อียิปต์)", "id": "Bahasa Arab (Mesir)" },
  { "code": "ar-IQ", "en": "Arabic (Iraq)", "zh": "阿拉伯语(伊拉克)", "th": "อาราบิก (อิรัก)", "id": "Bahasa Arab (Irak)" },
  { "code": "ar-JO", "en": "Arabic (Jordan)", "zh": "阿拉伯语(约旦)", "th": "อาราบิก (จอร์แดน)", "id": "Bahasa Arab (Yordania)" },
  { "code": "ar-KW", "en": "Arabic (Kuwait)", "zh": "阿拉伯语(科威特)", "th": "อาราบิก (คูเวต)", "id": "Bahasa Arab (Kuwait)" },
  { "code": "ar-LB", "en": "Arabic (Lebanon)", "zh": "阿拉伯语(黎巴嫩)", "th": "อาราบิก (เลบานอน)", "id": "Bahasa Arab (Lebanon)" },
  { "code": "ar-LY", "en": "Arabic (Libya)", "zh": "阿拉伯语(利比亚)", "th": "อาราบิก (ลิเบีย)", "id": "Bahasa Arab (Libya)" },
  { "code": "ar-MA", "en": "Arabic (Morocco)", "zh": "阿拉伯语(摩洛哥)", "th": "อาราบิก (โมร็อกโก)", "id": "Bahasa Arab (Maroko)" },
  { "code": "ar-OM", "en": "Arabic (Oman)", "zh": "阿拉伯语(阿曼)", "th": "อาราบิก (โอมาน)", "id": "Bahasa Arab (Oman)" },
  { "code": "ar-QA", "en": "Arabic (Qatar)", "zh": "阿拉伯语(卡塔尔)", "th": "อาราบิก (คาตาร์)", "id": "Bahasa Arab (Qatar)" },
  { "code": "ar-SA", "en": "Arabic (Saudi Arabia)", "zh": "阿拉伯语(沙特阿拉伯)", "th": "อาราบิก (ซาอุดีอาระเบีย)", "id": "Bahasa Arab (Arab Saudi)" },
  { "code": "ar-SY", "en": "Arabic (Syria)", "zh": "阿拉伯语(叙利亚)", "th": "อาราบิก (ซีเรีย)", "id": "Bahasa Arab (Suriah)" },
  { "code": "ar-TN", "en": "Arabic (Tunisia)", "zh": "阿拉伯语(突尼斯)", "th": "อาราบิก (ทูนิเซีย)", "id": "Bahasa Arab (Tunisia)" },
  { "code": "ar-YE", "en": "Arabic (Yemen)", "zh": "阿拉伯语(也门)", "th": "อาราบิก (เยเมน)", "id": "Bahasa Arab (Yaman)" },
  { "code": "az", "en": "Azeri (Latin)", "zh": "阿塞拜疆语", "th": "อาเซอร์ไบจัน (ละติน)", "id": "Azeri (Latin)" },
  { "code": "az-AZ", "en": "Azeri (Cyrillic) (Azerbaijan)", "zh": "阿塞拜疆语(西里尔文)", "th": "อาเซอร์ไบจัน (ไซริลลิก) (อาเซอร์ไบจาน)", "id": "Azeri (Cyrillic) (Azerbaijan)" },
  { "code": "be", "en": "Belarusian", "zh": "白俄罗斯语", "th": "เบลารุส", "id": "Bahasa Belarus" },
  { "code": "be-BY", "en": "Belarusian (Belarus)", "zh": "白俄罗斯语", "th": "เบลารุส (เบลารุส)", "id": "Bahasa Belarus (Belarus)" },
  { "code": "bg", "en": "Bulgarian", "zh": "保加利亚语", "th": "บัลแกเรีย", "id": "Bahasa Bulgaria" },
  { "code": "bg-BG", "en": "Bulgarian (Bulgaria)", "zh": "保加利亚语", "th": "บัลแกเรีย (บัลแกเรีย)", "id": "Bahasa Bulgaria (Bulgaria)" },
  { "code": "bs-BA", "en": "Bosnian (Bosnia and Herzegovina)", "zh": "波斯尼亚语(波斯尼亚和黑塞哥维那)", "th": "บอสเนีย (บอสเนียและเฮอร์เซโกวินา)", "id": "Bahasa Bosnia (Bosnia dan Herzegovina)" },
  { "code": "ca", "en": "Catalan", "zh": "加泰罗尼亚语", "th": "คาตาลัน", "id": "Katalan" },
  { "code": "ca-ES", "en": "Catalan (Spain)", "zh": "加泰罗尼亚语", "th": "คาตาลัน (สเปน)", "id": "Katalan (Spanyol)" },
  { "code": "cs", "en": "Czech", "zh": "捷克语", "th": "เช็ก", "id": "Bahasa Ceko" },
  { "code": "cs-CZ", "en": "Czech (Czech Republic)", "zh": "捷克语", "th": "เช็ก (สาธารณรัฐเช็ก)", "id": "Bahasa Ceko (Republik Ceko)" },
  { "code": "cy", "en": "Welsh", "zh": "威尔士语", "th": "เวล์ช", "id": "Welsh" },
  { "code": "cy-GB", "en": "Welsh (United Kingdom)", "zh": "威尔士语", "th": "เวล์ช (สหราชอาณาจักร)", "id": "Welsh (Kerajaan Inggris)" },
  { "code": "da", "en": "Danish", "zh": "丹麦语", "th": "เดนมาร์ก", "id": "Bahasa Denmark" },
  { "code": "da-DK", "en": "Danish (Denmark)", "zh": "丹麦语", "th": "เดนมาร์ก (เดนมาร์ก)", "id": "Bahasa Denmark (Denmark)" },
  { "code": "de", "en": "German", "zh": "德语", "th": "เยอรมัน", "id": "Bahasa Jerman" },
  { "code": "de-AT", "en": "German (Austria)", "zh": "德语(奥地利)", "th": "เยอรมัน (ออสเตรีย)", "id": "Bahasa Jerman (Austria)" },
  { "code": "de-CH", "en": "German (Switzerland)", "zh": "德语(瑞士)", "th": "เยอรมัน (สวิสเซอร์แลนด์)", "id": "Bahasa Jerman (Swiss)" },
  { "code": "de-DE", "en": "German (Germany)", "zh": "德语(德国)", "th": "เยอรมัน (เยอรมนี)", "id": "Bahasa Jerman (Jerman)" },
  { "code": "de-LI", "en": "German (Liechtenstein)", "zh": "德语(列支敦士登)", "th": "เยอรมัน (ลิกเตนสไตน์)", "id": "Bahasa Jerman (Liechtenstein)" },
  { "code": "de-LU", "en": "German (Luxembourg)", "zh": "德语(卢森堡)", "th": "เยอรมัน (ลักเซมเบิร์ก)", "id": "Bahasa Jerman (Luksemburg)" },
  { "code": "dv", "en": "Divehi", "zh": "迪维希语", "th": "ดีเวหี", "id": "Divehi" },
  { "code": "dv-MV", "en": "Divehi (Maldives)", "zh": "迪维希语", "th": "ดีเวหี (มัลดีฟส์)", "id": "Divehi (Maladewa)" },
  { "code": "el", "en": "Greek", "zh": "希腊语", "th": "กรีก", "id": "Bahasa Yunani" },
  { "code": "el-GR", "en": "Greek (Greece)", "zh": "希腊语", "th": "กรีก (กรีซ)", "id": "Bahasa Yunani (Yunani)" },
  { "code": "en", "en": "English", "zh": "英语", "th": "อังกฤษ", "id": "Bahasa Inggris" },
  { "code": "en-AU", "en": "English (Australia)", "zh": "英语(澳大利亚)", "th": "อังกฤษ (ออสเตรเลีย)", "id": "Bahasa Inggris (Australia)" },
  { "code": "en-BZ", "en": "English (Belize)", "zh": "英语(伯利兹)", "th": "อังกฤษ (เบลีซ)", "id": "Bahasa Inggris (Belize)" },
  { "code": "en-CA", "en": "English (Canada)", "zh": "英语(加拿大)", "th": "อังกฤษ (แคนาดา)", "id": "Bahasa Inggris (Kanada)" },
  { "code": "en-CB", "en": "English (Caribbean)", "zh": "英语(加勒比海)", "th": "อังกฤษ (คาริบเบียน)", "id": "Bahasa Inggris (Karibia)" },
  { "code": "en-GB", "en": "English (United Kingdom)", "zh": "英语(英国)", "th": "อังกฤษ (สหราชอาณาจักร)", "id": "Bahasa Inggris (Kerajaan Inggris)" },
  { "code": "en-IE", "en": "English (Ireland)", "zh": "英语(爱尔兰)", "th": "อังกฤษ (ไอร์แลนด์)", "id": "Bahasa Inggris (Irlandia)" },
  { "code": "en-IN", "en": "English (India)", "zh": "英语(印度)", "th": "อังกฤษ (อินเดีย)", "id": "Bahasa Inggris (India)" },
  { "code": "en-JM", "en": "English (Jamaica)", "zh": "英语(牙买加)", "th": "อังกฤษ (จาไมกา)", "id": "Bahasa Inggris (Jamaika)" },
  { "code": "en-NZ", "en": "English (New Zealand)", "zh": "英语(新西兰)", "th": "อังกฤษ (นิวซีแลนด์)", "id": "Bahasa Inggris (Selandia Baru)" },
  { "code": "en-PH", "en": "English (Philippines)", "zh": "英语(菲律宾)", "th": "อังกฤษ (ฟิลิปปินส์)", "id": "Bahasa Inggris (Filipina)" },
  { "code": "en-TT", "en": "English (Trinidad and Tobago)", "zh": "英语(特立尼达和多巴哥)", "th": "อังกฤษ (ตรินิแดดและโตเบโก)", "id": "Bahasa Inggris (Trinidad dan Tobago)" },
  { "code": "en-US", "en": "English (United States)", "zh": "英语(美国)", "th": "อังกฤษ (สหรัฐอเมริกา)", "id": "Bahasa Inggris (Amerika Serikat)" },
  { "code": "en-ZA", "en": "English (South Africa)", "zh": "英语(南非)", "th": "อังกฤษ (แอฟริกาใต้)", "id": "Bahasa Inggris (Afrika Selatan)" },
  { "code": "en-ZW", "en": "English (Zimbabwe)", "zh": "英语(津巴布韦)", "th": "อังกฤษ (ซิมบับเว)", "id": "Bahasa Inggris (Zimbabwe)" },
  { "code": "eo", "en": "Esperanto", "zh": "世界语", "th": "เอสเปรันโต", "id": "Esperanto" },
  { "code": "es", "en": "Spanish", "zh": "西班牙语", "th": "สเปน", "id": "Bahasa Spanyol" },
  { "code": "es-AR", "en": "Spanish (Argentina)", "zh": "西班牙语(阿根廷)", "th": "สเปน (อาร์เจนตินา)", "id": "Bahasa Spanyol (Argentina)" },
  { "code": "es-BO", "en": "Spanish (Bolivia)", "zh": "西班牙语(玻利维亚)", "th": "สเปน (โบลิเวีย)", "id": "Bahasa Spanyol (Bolivia)" },
  { "code": "es-CL", "en": "Spanish (Chile)", "zh": "西班牙语(智利)", "th": "สเปน (ชิลี)", "id": "Bahasa Spanyol (Chile)" },
  { "code": "es-CO", "en": "Spanish (Colombia)", "zh": "西班牙语(哥伦比亚)", "th": "สเปน (โคลัมเบีย)", "id": "Bahasa Spanyol (Kolombia)" },
  { "code": "es-CR", "en": "Spanish (Costa Rica)", "zh": "西班牙语(哥斯达黎加)", "th": "สเปน (โคสตาริกา)", "id": "Bahasa Spanyol (Kosta Rika)" },
  { "code": "es-DO", "en": "Spanish (Dominican Republic)", "zh": "西班牙语(多米尼加共和国)", "th": "สเปน (สาธารณรัฐโดมินกัน)", "id": "Bahasa Spanyol (Republik Dominika)" },
  { "code": "es-EC", "en": "Spanish (Ecuador)", "zh": "西班牙语(厄瓜多尔)", "th": "สเปน (เอกวาดอร์)", "id": "Bahasa Spanyol (Ekuador)" },
  { "code": "es-ES", "en": "Spanish (Spain)", "zh": "西班牙语(西班牙)", "th": "สเปน (สเปน)", "id": "Bahasa Spanyol (Spanyol)" },
  { "code": "es-GT", "en": "Spanish (Guatemala)", "zh": "西班牙语(危地马拉)", "th": "สเปน (กัวเตมาลา)", "id": "Bahasa Spanyol (Guatemala)" },
  { "code": "es-HN", "en": "Spanish (Honduras)", "zh": "西班牙语(洪都拉斯)", "th": "สเปน (ฮอนดูรัส)", "id": "Bahasa Spanyol (Honduras)" },
  { "code": "es-MX", "en": "Spanish (Mexico)", "zh": "西班牙语(墨西哥)", "th": "สเปน (เม็กซิโก)", "id": "Bahasa Spanyol (Meksiko)" },
  { "code": "es-NI", "en": "Spanish (Nicaragua)", "zh": "西班牙语(尼加拉瓜)", "th": "สเปน (นิการากัว)", "id": "Bahasa Spanyol (Nikaragua)" },
  { "code": "es-PA", "en": "Spanish (Panama)", "zh": "西班牙语(巴拿马)", "th": "สเปน (ปานามา)", "id": "Bahasa Spanyol (Panama)" },
  { "code": "es-PE", "en": "Spanish (Peru)", "zh": "西班牙语(秘鲁)", "th": "สเปน (เปรู)", "id": "Bahasa Spanyol (Peru)" },
  { "code": "es-PR", "en": "Spanish (Puerto Rico)", "zh": "西班牙语(波多黎各)", "th": "สเปน (เปอร์โตริโก)", "id": "Bahasa Spanyol (Puerto Rico)" },
  { "code": "es-PY", "en": "Spanish (Paraguay)", "zh": "西班牙语(巴拉圭)", "th": "สเปน (ปารากวัย)", "id": "Bahasa Spanyol (Paraguay)" },
  { "code": "es-SV", "en": "Spanish (El Salvador)", "zh": "西班牙语(萨尔瓦多)", "th": "สเปน (เอลซัลวาดอร์)", "id": "Bahasa Spanyol (El Salvador)" },
  { "code": "es-UY", "en": "Spanish (Uruguay)", "zh": "西班牙语(乌拉圭)", "th": "สเปน (อุรุกวัย)", "id": "Bahasa Spanyol (Uruguay)" },
  { "code": "es-VE", "en": "Spanish (Venezuela)", "zh": "西班牙语(委内瑞拉)", "th": "สเปน (เวเนซุเอลา)", "id": "Bahasa Spanyol (Venezuela)" },
  { "code": "et", "en": "Estonian", "zh": "爱沙尼亚语", "th": "เอสโตเนีย", "id": "Bahasa Estonia" },
  { "code": "et-EE", "en": "Estonian (Estonia)", "zh": "爱沙尼亚语", "th": "เอสโตเนีย (เอสโตเนีย)", "id": "Bahasa Estonia (Estonia)" },
  { "code": "eu", "en": "Basque", "zh": "巴斯克语", "th": "บาสก์", "id": "Basque" },
  { "code": "eu-ES", "en": "Basque (Spain)", "zh": "巴斯克语", "th": "บาสก์ (สเปน)", "id": "Basque (Spanyol)" },
  { "code": "fa", "en": "Farsi", "zh": "波斯语", "th": "فارسی", "id": "Farsi" },
  { "code": "fa-IR", "en": "Farsi (Iran)", "zh": "波斯语", "th": "فارسی (อิหร่าน)", "id": "Farsi (Iran)" },
  { "code": "fi", "en": "Finnish", "zh": "芬兰语", "th": "ฟินแลนด์", "id": "Bahasa Finlandia" },
  { "code": "fi-FI", "en": "Finnish (Finland)", "zh": "芬兰语", "th": "ฟินแลนด์ (ฟินแลนด์)", "id": "Bahasa Finlandia (Finlandia)" },
  { "code": "fo", "en": "Faroese", "zh": "法罗语", "th": "ฟาโรอีส์", "id": "Faroese" },
  { "code": "fo-FO", "en": "Faroese (Faroe Islands)", "zh": "法罗语", "th": "ฟาโรอีส์ (หมู่เกาะฟาโร)", "id": "Faroese (Kepulauan Faro)" },
  { "code": "fr", "en": "French", "zh": "法语", "th": "ฝรั่งเศส", "id": "Bahasa Prancis" },
  { "code": "fr-BE", "en": "French (Belgium)", "zh": "法语(比利时)", "th": "ฝรั่งเศส (เบลเยียม)", "id": "Bahasa Prancis (Belgia)" },
  { "code": "fr-CA", "en": "French (Canada)", "zh": "法语(加拿大)", "th": "ฝรั่งเศส (แคนาดา)", "id": "Bahasa Prancis (Kanada)" },
  { "code": "fr-CH", "en": "French (Switzerland)", "zh": "法语(瑞士)", "th": "ฝรั่งเศส (สวิสเซอร์แลนด์)", "id": "Bahasa Prancis (Swiss)" },
  { "code": "fr-FR", "en": "French (France)", "zh": "法语(法国)", "th": "ฝรั่งเศส (ฝรั่งเศส)", "id": "Bahasa Prancis (Prancis)" },
  { "code": "fr-LU", "en": "French (Luxembourg)", "zh": "法语(卢森堡)", "th": "ฝรั่งเศส (ลักเซมเบิร์ก)", "id": "Bahasa Prancis (Luksemburg)" },
  { "code": "fr-MC", "en": "French (Monaco)", "zh": "法语(摩纳哥)", "th": "ฝรั่งเศส (โมนาโก)", "id": "Bahasa Prancis (Monaco)" },
  { "code": "gl", "en": "Galician", "zh": "加利西亚语", "th": "กาลิเซีย", "id": "Galician" },
  { "code": "gl-ES", "en": "Galician (Spain)", "zh": "加利西亚语", "th": "กาลิเซีย (สเปน)", "id": "Galician (Spanyol)" },
  { "code": "gu", "en": "Gujarati", "zh": "古吉拉特语", "th": "กุจาราตี", "id": "Gujarati" },
  { "code": "gu-IN", "en": "Gujarati (India)", "zh": "古吉拉特语", "th": "กุจาราตี (อินเดีย)", "id": "Gujarati (India)" },
  { "code": "he", "en": "Hebrew", "zh": "希伯来语", "th": "ฮีบรู", "id": "Bahasa Ibrani" },
  { "code": "he-IL", "en": "Hebrew (Israel)", "zh": "希伯来语", "th": "ฮีบรู (อิสราเอล)", "id": "Bahasa Ibrani (Israel)" },
  { "code": "hi", "en": "Hindi", "zh": "印地语", "th": "ฮินดี", "id": "Bahasa Hindi" },
  { "code": "hi-IN", "en": "Hindi (India)", "zh": "印地语", "th": "ฮินดี (อินเดีย)", "id": "Bahasa Hindi (India)" },
  { "code": "hr", "en": "Croatian", "zh": "克罗地亚语", "th": "โครเอเชีย", "id": "Bahasa Kroasia" },
  { "code": "hr-BA", "en": "Croatian (Bosnia and Herzegovina)", "zh": "克罗地亚语(波斯尼亚和黑塞哥维那)", "th": "โครเอเชีย (บอสเนียและเฮอร์เซโกวินา)", "id": "Bahasa Kroasia (Bosnia dan Herzegovina)" },
  { "code": "hr-HR", "en": "Croatian (Croatia)", "zh": "克罗地亚语", "th": "โครเอเชีย (โครเอเชีย)", "id": "Bahasa Kroasia (Kroasia)" },
  { "code": "hu", "en": "Hungarian", "zh": "匈牙利语", "th": "ฮังการี", "id": "Bahasa Hongaria" },
  { "code": "hu-HU", "en": "Hungarian (Hungary)", "zh": "匈牙利语", "th": "ฮังการี (ฮังการี)", "id": "Bahasa Hongaria (Hongaria)" },
  { "code": "hy", "en": "Armenian", "zh": "亚美尼亚语", "th": "อาร์เมเนีย", "id": "Bahasa Armenia" },
  { "code": "hy-AM", "en": "Armenian (Armenia)", "zh": "亚美尼亚语", "th": "อาร์เมเนีย (อาร์เมเนีย)", "id": "Bahasa Armenia (Armenia)" },
  { "code": "id", "en": "Indonesian", "zh": "印尼语", "th": "อินโดนีเซีย", "id": "Bahasa Indonesia" },
  { "code": "id-ID", "en": "Indonesian (Indonesia)", "zh": "印尼语", "th": "อินโดนีเซีย (อินโดนีเซีย)", "id": "Bahasa Indonesia (Indonesia)" },
  { "code": "is", "en": "Icelandic", "zh": "冰岛语", "th": "ไอซ์แลนด์", "id": "Bahasa Islandia" },
  { "code": "is-IS", "en": "Icelandic (Iceland)", "zh": "冰岛语", "th": "ไอซ์แลนด์ (ไอซ์แลนด์)", "id": "Bahasa Islandia (Islandia)" },
  { "code": "it", "en": "Italian", "zh": "意大利语", "th": "อิตาลี", "id": "Bahasa Italia" },
  { "code": "it-CH", "en": "Italian (Switzerland)", "zh": "意大利语(瑞士)", "th": "อิตาลี (สวิสเซอร์แลนด์)", "id": "Bahasa Italia (Swiss)" },
  { "code": "it-IT", "en": "Italian (Italy)", "zh": "意大利语(意大利)", "th": "อิตาลี (อิตาลี)", "id": "Bahasa Italia (Italia)" },
  { "code": "ja", "en": "Japanese", "zh": "日语", "th": "ญี่ปุ่น", "id": "Bahasa Jepang" },
  { "code": "ja-JP", "en": "Japanese (Japan)", "zh": "日语", "th": "ญี่ปุ่น (ญี่ปุ่น)", "id": "Bahasa Jepang (Jepang)" },
  { "code": "ka", "en": "Georgian", "zh": "格鲁吉亚语", "th": "จอร์เจีย", "id": "Bahasa Georgia" },
  { "code": "ka-GE", "en": "Georgian (Georgia)", "zh": "格鲁吉亚语", "th": "จอร์เจีย (จอร์เจีย)", "id": "Bahasa Georgia (Georgia)" },
  { "code": "kk", "en": "Kazakh", "zh": "哈萨克语", "th": "คาซัค", "id": "Bahasa Kazakhstan" },
  { "code": "kk-KZ", "en": "Kazakh (Kazakhstan)", "zh": "哈萨克语", "th": "คาซัค (คาซัคสถาน)", "id": "Bahasa Kazakhstan (Kazakhstan)" },
  { "code": "kn", "en": "Kannada", "zh": "卡纳达语", "th": "กันนาดา", "id": "Kannada" },
  { "code": "kn-IN", "en": "Kannada (India)", "zh": "卡纳达语", "th": "กันนาดา (อินเดีย)", "id": "Kannada (India)" },
  { "code": "ko", "en": "Korean", "zh": "韩语", "th": "เกาหลี", "id": "Bahasa Korea" },
  { "code": "ko-KR", "en": "Korean (South Korea)", "zh": "韩语", "th": "เกาหลี (เกาหลีใต้)", "id": "Bahasa Korea (Korea Selatan)" },
  { "code": "kok", "en": "Konkani", "zh": "孔卡尼语", "th": "โคนกานี", "id": "Konkani" },
  { "code": "kok-IN", "en": "Konkani (India)", "zh": "孔卡尼语", "th": "โคนกานี (อินเดีย)", "id": "Konkani (India)" },
  { "code": "ky", "en": "Kyrgyz", "zh": "吉尔吉斯语", "th": "กีร์กิส", "id": "Bahasa Kirgiz" },
  { "code": "ky-KG", "en": "Kyrgyz (Kyrgyzstan)", "zh": "吉尔吉斯语", "th": "กีร์กิส (กีร์กิสสถาน)", "id": "Bahasa Kirgiz (Kyrgyzstan)" },
  { "code": "lt", "en": "Lithuanian", "zh": "立陶宛语", "th": "ลิทัวเนีย", "id": "Bahasa Lithuania" },
  { "code": "lt-LT", "en": "Lithuanian (Lithuania)", "zh": "立陶宛语", "th": "ลิทัวเนีย (ลิทัวเนีย)", "id": "Bahasa Lithuania (Lithuania)" },
  { "code": "lv", "en": "Latvian", "zh": "拉脱维亚语", "th": "ลัตเวีย", "id": "Bahasa Latvia" },
  { "code": "lv-LV", "en": "Latvian (Latvia)", "zh": "拉脱维亚语", "th": "ลัตเวีย (ลัตเวีย)", "id": "Bahasa Latvia (Latvia)" },
  { "code": "mi", "en": "Maori", "zh": "毛利语", "th": "มอริ", "id": "Maori" },
  { "code": "mi-NZ", "en": "Maori (New Zealand)", "zh": "毛利语", "th": "มอริ (นิวซีแลนด์)", "id": "Maori (Selandia Baru)" },
  { "code": "mk", "en": "Macedonian", "zh": "马其顿语", "th": "แมเซโดเนีย", "id": "Bahasa Makedonia" },
  { "code": "mk-MK", "en": "Macedonian (North Macedonia)", "zh": "马其顿语", "th": "แมเซโดเนีย (แมเซโดเนียเหนือ)", "id": "Bahasa Makedonia (Makedonia Utara)" },
  { "code": "mn", "en": "Mongolian", "zh": "蒙古语", "th": "มองโกล", "id": "Bahasa Mongolia" },
  { "code": "mn-MN", "en": "Mongolian (Mongolia)", "zh": "蒙古语", "th": "มองโกล (มองโกล)", "id": "Bahasa Mongolia (Mongolia)" },
  { "code": "mr", "en": "Marathi", "zh": "马拉地语", "th": "มาราธี", "id": "Marathi" },
  { "code": "mr-IN", "en": "Marathi (India)", "zh": "马拉地语", "th": "มาราธี (อินเดีย)", "id": "Marathi (India)" },
  { "code": "ms", "en": "Malay", "zh": "马来语", "th": "มลายู", "id": "Bahasa Melayu" },
  { "code": "ms-BN", "en": "Malay (Brunei)", "zh": "马来语(文莱)", "th": "มลายู (บรูไน)", "id": "Bahasa Melayu (Brunei)" },
  { "code": "ms-MY", "en": "Malay (Malaysia)", "zh": "马来语(马来西亚)", "th": "มลายู (มาเลเซีย)", "id": "Bahasa Melayu (Malaysia)" },
  { "code": "mt", "en": "Maltese", "zh": "马耳他语", "th": "มอลตา", "id": "Bahasa Malta" },
  { "code": "mt-MT", "en": "Maltese (Malta)", "zh": "马耳他语", "th": "มอลตา (มอลตา)", "id": "Bahasa Malta (Malta)" },
  { "code": "nb", "en": "Norwegian (Bokmål)", "zh": "挪威语(书面挪威语)", "th": "นอร์เวย์ (บอคมาล)", "id": "Norwegia (Bokmål)" },
  { "code": "nb-NO", "en": "Norwegian (Bokmål) (Norway)", "zh": "挪威语(书面挪威语)(挪威)", "th": "นอร์เวย์ (บอคมาล) (นอร์เวย์)", "id": "Norwegia (Bokmål) (Norwegia)" },
  { "code": "nl", "en": "Dutch", "zh": "荷兰语", "th": "ดัตช์", "id": "Bahasa Belanda" },
  { "code": "nl-BE", "en": "Dutch (Belgium)", "zh": "荷兰语(比利时)", "th": "ดัตช์ (เบลเยียม)", "id": "Bahasa Belanda (Belgia)" },
  { "code": "nl-NL", "en": "Dutch (Netherlands)", "zh": "荷兰语(荷兰)", "th": "ดัตช์ (เนเธอร์แลนด์)", "id": "Bahasa Belanda (Belanda)" },
  { "code": "nn-NO", "en": "Norwegian (Nynorsk) (Norway)", "zh": "挪威语(新挪威语)(挪威)", "th": "นอร์เวย์ (นายนอร์สก) (นอร์เวย์)", "id": "Norwegia (Nynorsk) (Norwegia)" },
  { "code": "ns", "en": "Northern Sotho", "zh": "北索托语", "th": "โซโทเหนือ", "id": "Sotho Utara" },
  { "code": "ns-ZA", "en": "Northern Sotho (South Africa)", "zh": "北索托语", "th": "โซโทเหนือ (แอฟริกาใต้)", "id": "Sotho Utara (Afrika Selatan)" },
  { "code": "pa", "en": "Punjabi", "zh": "旁遮普语", "th": "ปันจาบี", "id": "Punjabi" },
  { "code": "pa-IN", "en": "Punjabi (India)", "zh": "旁遮普语", "th": "ปันจาบี (อินเดีย)", "id": "Punjabi (India)" },
  { "code": "pl", "en": "Polish", "zh": "波兰语", "th": "โปแลนด์", "id": "Bahasa Polandia" },
  { "code": "pl-PL", "en": "Polish (Poland)", "zh": "波兰语", "th": "โปแลนด์ (โปแลนด์)", "id": "Bahasa Polandia (Polandia)" },
  { "code": "pt", "en": "Portuguese", "zh": "葡萄牙语", "th": "โปรตุเกส", "id": "Bahasa Portugis" },
  { "code": "pt-BR", "en": "Portuguese (Brazil)", "zh": "葡萄牙语(巴西)", "th": "โปรตุเกส (บราซิล)", "id": "Bahasa Portugis (Brasil)" },
  { "code": "pt-PT", "en": "Portuguese (Portugal)", "zh": "葡萄牙语(葡萄牙)", "th": "โปรตุเกส (โปรตุเกส)", "id": "Bahasa Portugis (Portugal)" },
  { "code": "qu", "en": "Quechua", "zh": "克丘亚语", "th": "เควชัว", "id": "Quechua" },
  { "code": "qu-BO", "en": "Quechua (Bolivia)", "zh": "克丘亚语(玻利维亚)", "th": "เควชัว (โบลิเวีย)", "id": "Quechua (Bolivia)" },
  { "code": "qu-EC", "en": "Quechua (Ecuador)", "zh": "克丘亚语(厄瓜多尔)", "th": "เควชัว (เอกวาดอร์)", "id": "Quechua (Ekuador)" },
  { "code": "qu-PE", "en": "Quechua (Peru)", "zh": "克丘亚语(秘鲁)", "th": "เควชัว (เปรู)", "id": "Quechua (Peru)" },
  { "code": "ro", "en": "Romanian", "zh": "罗马尼亚语", "th": "โรมาเนีย", "id": "Bahasa Rumania" },
  { "code": "ro-RO", "en": "Romanian (Romania)", "zh": "罗马尼亚语", "th": "โรมาเนีย (โรมาเนีย)", "id": "Bahasa Rumania (Rumania)" }
];